name: digital_restaurant_menu_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  flutter_svg: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/pizza ittaliano.png
    - assets/images/Crame brulee.jpg
    - assets/images/Lava Cake.jpg
    - assets/images/Cheese Cake.jpg
    - assets/images/image14.jpg
    - assets/images/Red Wine.jpg
    - assets/images/White Wine.jpg
    - assets/images/buffalo-chicken-dip.jpg
    - assets/images/Blue-Cheese-Dip.jpg
    - assets/images/Bacon-Cheddar-Dip.jpg
    - assets/images/Caprese Skewers.jpg
    - assets/images/Strawberry-Balsamic-Bruschetta.jpg
    - assets/images/stuffed-dates.jpg
    - assets/images/grilled steak.jpg
    - assets/images/roast chicken.jpg
    - assets/images/lamb chops.jpg
    - assets/images/chicken wings.jpg
    - assets/images/Beef-Burgers.jpg
    - assets/images/grilled salmon.jpeg
    - assets/images/lobster-tail.jpg
    - assets/images/tuna_steak.jpg
    - assets/images/Calamari.jpg
    - assets/images/cauliflower curry.jpg
    - assets/images/eggplant-parmesan.jpg
    - assets/images/greeksalad.jpg
    - assets/images/Lasagna.jpg
    - assets/images/Carbonara.jpg
    - assets/images/Mac-Cheese.jpg
    - assets/images/Strawberry Cake.jpg
    - assets/images/Blue Berry Cheese Cake.jpg
    - assets/images/banana split.jpg
    - assets/images/Ice-Cream-Sundae.jpg
    - assets/images/Gelato.jpg
    - assets/images/Blue Berry Pie.jpg
    - assets/images/Apple Pie.jpg
    - assets/images/Cherry Pie.jpg
    - assets/images/Chocolate Pudding.jpg
    - assets/images/Vanilla Pudding.jpg
    - assets/images/Bread Pudding.jpg
    

  fonts:
    - family: Rosarivo-Regular
      fonts:
        - asset: assets/Rosarivo-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
